# fly.toml app configuration file generated for storj-mov-floral-shape-7087 on 2025-07-17T10:15:26-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'storj-bootstrap-worker'
primary_region = 'iad'
swap_size_mb = 256

[build]
  dockerfile = 'Dockerfile'
[mounts]
  source = "dragonfly_data"
  destination = "/data"

[env]
  # Set these environment variables using: fly secrets set VARIABLE_NAME=value
  # STORJ_ACCESS_KEY = "your-storj-access-key"
  # STORJ_SECRET_KEY = "your-storj-secret-key"
  # STORJ_BUCKET_URL = "your-storj-bucket-url"
  # STORJ_DEFAULT_REGION = "your-storj-default-region"

  # (Optional: will be generated)
  # DRAGONFLY_PASSWORD = "your-dragonfly-password"

  # Redis Proxy Configuration (REQUIRED for proxy process)
  # PROXY_PASSWORD = "your-secure-proxy-password"
  # REDIS_URL = "redis://username:password@host:port"  # This should already be set if using Fly Upstash else Set via: fly secrets set REDIS_URL=your-redis-url
  
  LOG_LEVEL = 'DEBUG'
  PORT = '8080'

[processes]
  app = './start.sh'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['http', 'tls']

[[services]]
  protocol = 'tcp'
  internal_port = 6379
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 6379

[[vm]]
  size = 'shared-cpu-1x'

[[metrics]]
  port = 9090
  path = '/metrics'
  processes = ['app']
